spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    data:
        mongodb:
            host: localhost
            port: 27017
            user: mydb
server:
    port: 8081

